import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";
import path from "path";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Ensure dist directory exists
if (!fs.existsSync("dist")) {
    fs.mkdirSync("dist");
}

// Copy static files
try {
    fs.copyFileSync("manifest.json", "dist/manifest.json");
    fs.copyFileSync("styles.css", "dist/styles.css");
} catch (e) {
    console.error("Failed to copy static files:", e);
    process.exit(1);
}

// Define Vault Path
if (!process.env.OBSIDIAN_VAULT) {
    console.error("OBSIDIAN_VAULT environment variable is not set.");
    process.exit(1);
}

const VAULT_PLUGIN_DIR = path.join(process.env.OBSIDIAN_VAULT, ".obsidian", "plugins", "yaoh");

function copyToVault() {
    if (!fs.existsSync(VAULT_PLUGIN_DIR)) {
        fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
    }

    fs.copyFileSync("manifest.json", path.join(VAULT_PLUGIN_DIR, "manifest.json"));
    fs.copyFileSync("styles.css", path.join(VAULT_PLUGIN_DIR, "styles.css"));
    fs.copyFileSync("dist/main.js", path.join(VAULT_PLUGIN_DIR, "main.js"));

    console.log(`[Updated] Plugin copied to ${VAULT_PLUGIN_DIR}`);
}

const copyToVaultPlugin = {
    name: 'copy-to-vault',
    setup(build) {
        build.onEnd(() => {
            copyToVault();
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/closebrackets",
        "@codemirror/commands",
        "@codemirror/comment",
        "@codemirror/fold",
        "@codemirror/gutter",
        "@codemirror/highlight",
        "@codemirror/history",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/matchbrackets",
        "@codemirror/panel",
        "@codemirror/rangeset",
        "@codemirror/rectangular-selection",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/stream-parser",
        "@codemirror/text",
        "@codemirror/tooltip",
        "@codemirror/view",
        ...builtinModules],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "dist/main.js",
    plugins: [copyToVaultPlugin],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
